const cards = [
	{
		back: './imagenes/cuadro1.png',
		front: './imagenes/imagen1.png',
		item: 1,
		question_image: './imagenes/pregunta1.jpg',
		a: {
			top: '34.5%',
			left: '8.9%',
			incorrect_image: './imagenes/rojo1.png',
		},
		b: {
			top: '47%',
			left: '8.9%',
			alert_image: './imagenes/verde1.png',
		},
		c: {
			top: '59.6%',
			left: '8.9%',
			incorrect_image: './imagenes/rojo1.png',
		},
		d: {
			top: '72.3%',
			left: '8.9%',
			incorrect_image: './imagenes/rojo1.png',
		},
		correct: 'b',
		correct_image: './imagenes/respuesta-1.png',
	},
	{
		back: './imagenes/cuadro1.png',
		front: './imagenes/imagen2.png',
		item: 2,
		question_image: './imagenes/pregunta2.jpg',
		a: {
			top: '33.5%',
			left: '8.9%',
			incorrect_image: './imagenes/rojo2.png',
		},
		b: {
			top: '46.3%',
			left: '8.9%',
			incorrect_image: './imagenes/rojo2.png',
		},
		c: {
			top: '58.7%',
			left: '8.9%',
			incorrect_image: './imagenes/rojo2.png',
		},
		d: {
			top: '71.2%',
			left: '10%',
			alert_image: './imagenes/verde2.png',
		},
		correct: 'd',
		correct_image: './imagenes/respuesta-2.png',
	},
	{
		back: './imagenes/cuadro1.png',
		front: './imagenes/imagen3.png',
		item: 3,
		question_image: './imagenes/pregunta3.jpg',
		a: {
			top: '46%',
			left: '8.9%',
			incorrect_image: './imagenes/rojo3.png',
		},
		b: {
			top: '62.2%',
			left: '9.7%',
			alert_image: './imagenes/verde3.png',
		},
		c: {
			top: '0%',
			left: '0%',
			incorrect_image: './imagenes/rojo3.png',
		},
		d: {
			top: '0%',
			left: '0%',
			alert_image: './imagenes/verde3.png',
		},
		correct: 'b',
		correct_image: './imagenes/respuesta-3.png',
	},
	{
		back: './imagenes/cuadro1.png',
		front: './imagenes/imagen4.png',
		item: 4,
		question_image: './imagenes/pregunta4.jpg',
		a: {
			top: '29%',
			left: '8.9%',
            width: '43%',
			incorrect_image: './imagenes/rojo4.png',
		},
		b: {
			top: '42.2%',
			left: '8.9%',
            width: '43%',
			incorrect_image: './imagenes/rojo4.png',
		},
		c: {
			top: '54.8%',
			left: '8.9%',
            width: '43%',
			incorrect_image: './imagenes/rojo4.png',
		},
		d: {
			top: '66.8%',
			left: '8.3%',
            width: '43%',
			alert_image: './imagenes/verde4.png',
		},
		correct: 'd',
		correct_image: './imagenes/respuesta-4.png',
	},
	{
		back: './imagenes/cuadro1.png',
		front: './imagenes/imagen5.png',
		item: 5,
		question_image: './imagenes/pregunta5.jpg',
		a: {
			top: '35%',
			left: '7.9%',
            width: '44.5%',
			incorrect_image: './imagenes/rojo5.png',
		},
		b: {
			top: '47.3%',
			left: '7.9%',
            width: '44.5%',
			incorrect_image: './imagenes/rojo5.png',
		},
		c: {
			top: '60.1%',
			left: '7.9%',
            width: '44.5%',
			alert_image: './imagenes/verde5.png',
		},
		d: {
			top: '72.3%',
			left: '7.9%',
            width: '44.5%',
			incorrect_image: './imagenes/rojo5.png',
		},
		correct: 'c',
		correct_image: './imagenes/respuesta-5.png',
	},
	{
		back: './imagenes/cuadro1.png',
		front: './imagenes/imagen6.png',
		item: 6,
		question_image: './imagenes/pregunta6.jpg',
		a: {
			top: '33.7%',
			left: '8.9%',
            width: '43%',
			incorrect_image: './imagenes/rojo6.png',
		},
		b: {
			top: '45.9%',
			left: '8.9%',
            width: '43%',
			alert_image: './imagenes/verde6.png',
		},
		c: {
			top: '58.8%',
            width: '43%',
			left: '8.9%',
			incorrect_image: './imagenes/rojo6.png',
		},
		d: {
			top: '70.7%',
            width: '43%',
			left: '8.9%',
			incorrect_image: './imagenes/rojo6.png',
		},
		correct: 'b',
		correct_image: './imagenes/respuesta-6.png',
	},
	{
		back: './imagenes/cuadro1.png',
		front: './imagenes/imagen4.png',
		item: 4,
		question_image: './imagenes/pregunta4.jpg',
		a: {
			top: '29%',
			left: '8.9%',
            width: '43%',
			incorrect_image: './imagenes/rojo4.png',
		},
		b: {
			top: '42.2%',
			left: '8.9%',
            width: '43%',
			incorrect_image: './imagenes/rojo4.png',
		},
		c: {
			top: '54.8%',
			left: '8.9%',
            width: '43%',
			incorrect_image: './imagenes/rojo4.png',
		},
		d: {
			top: '66.8%',
			left: '8.3%',
            width: '43%',
			alert_image: './imagenes/verde4.png',
		},
		correct: 'd',
		correct_image: './imagenes/respuesta-4.png',
	},
	{
		back: './imagenes/cuadro1.png',
		front: './imagenes/imagen7.png',
		item: 7,
		question_image: './imagenes/pregunta7.jpg',
		a: {
			top: '33.7%',
			left: '8.3%',
            width: '43%',
			incorrect_image: './imagenes/rojo7.png',
		},
		b: {
			top: '46.1%',
			left: '8.3%',
            width: '43%',
			incorrect_image: './imagenes/rojo7.png',
		},
		c: {
			top: '58.6%',
			left: '8.3%',
            width: '43%',
			incorrect_image: './imagenes/rojo7.png',
		},
		d: {
			top: '70.9%',
			left: '8.3%',
            width: '43%',
			alert_image: './imagenes/verde7.png',
		},
		correct: 'd',
		correct_image: './imagenes/respuesta-7.png',
	},
	{
		back: './imagenes/cuadro1.png',
		front: './imagenes/imagen8.png',
		item: 8,
		question_image: './imagenes/pregunta8.jpg',
		a: {
			top: '46%',
			left: '9.9%',
			alert_image: './imagenes/verde8.png',
		},
		b: {
			top: '61.3%',
			left: '9.9%',
			incorrect_image: './imagenes/rojo8.png',
		},
		c: {
			top: '0%',
			left: '0%',
			incorrect_image: './imagenes/rojo8.png',
		},
		d: {
			top: '0%',
			left: '0%',
			incorrect_image: './imagenes/rojo8.png',
		},
		correct: 'a',
		correct_image: './imagenes/respuesta-8.png',
	},
	{
		back: './imagenes/cuadro1.png',
		front: './imagenes/imagen10.png',
		item: 10,
		question_image: './imagenes/pregunta10.jpg',
		a: {
			top: '35%',
			left: '8.9%',
			incorrect_image: './imagenes/rojo10.png',
		},
		b: {
			top: '47.3%',
			left: '8.9%',
			alert_image: './imagenes/verde10.png',
		},
		c: {
			top: '59.8%',
			left: '8.9%',
			incorrect_image: './imagenes/rojo10.png',
		},
		d: {
			top: '72.3%',
			left: '8.9%',
			incorrect_image: './imagenes/rojo10.png',
		},
		correct: 'b',
		correct_image: './imagenes/respuesta-10.png',
	},
	{
		back: './imagenes/cuadro1.png',
		front: './imagenes/imagen9.png',
		item: 9,
		question_image: './imagenes/pregunta9.jpg',
		a: {
			top: '30.3%',
			left: '8.3%',
			width: '47%',
			incorrect_image: './imagenes/rojo9.png',
		},
		b: {
			top: '42.6%',
			left: '8.9%',
			width: '47%',
			incorrect_image: './imagenes/rojo9.png',
		},
		c: {
			top: '55.2%',
			left: '8.9%',
			width: '47%',
			incorrect_image: './imagenes/rojo9.png',
		},
		d: {
			top: '67.3%',
			left: '8.3%',
			width: '47%',
			alert_image: './imagenes/verde9.png',
		},
		correct: 'd',
		correct_image: './imagenes/respuesta-9.png',
	},
	{
		back: './imagenes/cuadro1.png',
		front: './imagenes/imagen2.png',
		item: 2,
		question_image: './imagenes/pregunta2.jpg',
		a: {
			top: '33.5%',
			left: '8.9%',
			incorrect_image: './imagenes/rojo2.png',
		},
		b: {
			top: '46.3%',
			left: '8.9%',
			incorrect_image: './imagenes/rojo2.png',
		},
		c: {
			top: '58.7%',
			left: '8.9%',
			incorrect_image: './imagenes/rojo2.png',
		},
		d: {
			top: '71.2%',
			left: '10%',
			alert_image: './imagenes/verde2.png',
		},
		correct: 'd',
		correct_image: './imagenes/respuesta-2.png',
	},
	{
		back: './imagenes/cuadro1.png',
		front: './imagenes/imagen7.png',
		item: 7,
		question_image: './imagenes/pregunta1.jpg',
		a: {
			top: '33.7%',
			left: '8.3%',
            width: '43%',
			incorrect_image: './imagenes/rojo7.png',
		},
		b: {
			top: '46.1%',
			left: '8.3%',
            width: '43%',
			incorrect_image: './imagenes/rojo7.png',
		},
		c: {
			top: '58.6%',
			left: '8.3%',
            width: '43%',
			incorrect_image: './imagenes/rojo7.png',
		},
		d: {
			top: '70.9%',
			left: '8.3%',
            width: '43%',
			alert_image: './imagenes/verde7.png',
		},
		correct: 'd',
		correct_image: './imagenes/respuesta-7.png',
	},
	{
		back: './imagenes/cuadro1.png',
		front: './imagenes/imagen9.png',
		item: 9,
		question_image: './imagenes/pregunta1.jpg',
		a: {
			top: '30.3%',
			left: '8.9%',
			width: '47%',
			incorrect_image: './imagenes/rojo1.png',
		},
		b: {
			top: '42.6%',
			left: '8.9%',
			width: '47%',
			alert_image: './imagenes/verde1.png',
		},
		c: {
			top: '55.2%',
			left: '8.9%',
			width: '47%',
			incorrect_image: './imagenes/rojo1.png',
		},
		d: {
			top: '72.3%',
			left: '8.9%',
			width: '47%',
			incorrect_image: './imagenes/rojo1.png',
		},
		correct: 'b',
		correct_image: './imagenes/respuesta-9.png',
	},
	{
		back: './imagenes/cuadro1.png',
		front: './imagenes/imagen1.png',
		item: 1,
		question_image: './imagenes/pregunta1.jpg',
		a: {
			top: '34.5%',
			left: '8.9%',
			incorrect_image: './imagenes/rojo1.png',
		},
		b: {
			top: '47%',
			left: '8.9%',
			alert_image: './imagenes/verde1.png',
		},
		c: {
			top: '59.6%',
			left: '8.9%',
			incorrect_image: './imagenes/rojo1.png',
		},
		d: {
			top: '72.3%',
			left: '8.9%',
			incorrect_image: './imagenes/rojo1.png',
		},
		correct: 'b',
		correct_image: './imagenes/respuesta-1.png',
	},
	{
		back: './imagenes/cuadro1.png',
		front: './imagenes/imagen5.png',
		item: 5,
		question_image: './imagenes/pregunta1.jpg',
		a: {
			top: '35%',
			left: '7.9%',
            width: '44.5%',
			incorrect_image: './imagenes/rojo1.png',
		},
		b: {
			top: '47.3%',
			left: '7.9%',
            width: '44.5%',
			alert_image: './imagenes/verde1.png',
		},
		c: {
			top: '59.8%',
			left: '7.9%',
            width: '44.5%',
			incorrect_image: './imagenes/rojo1.png',
		},
		d: {
			top: '72.3%',
			left: '7.9%',
			width: '44.5%',
			incorrect_image: './imagenes/rojo1.png',
		},
		correct: 'c',
		correct_image: './imagenes/respuesta-5.png',
	},
	{
		back: './imagenes/cuadro1.png',
		front: './imagenes/imagen10.png',
		item: 10,
		question_image: './imagenes/pregunta10.jpg',
		a: {
			top: '35%',
			left: '8.9%',
			incorrect_image: './imagenes/rojo10.png',
		},
		b: {
			top: '47.3%',
			left: '8.9%',
			alert_image: './imagenes/verde10.png',
		},
		c: {
			top: '59.8%',
			left: '8.9%',
			incorrect_image: './imagenes/rojo10.png',
		},
		d: {
			top: '72.3%',
			left: '8.9%',
			incorrect_image: './imagenes/rojo10.png',
		},
		correct: 'b',
		correct_image: './imagenes/respuesta-10.png',
	},
	{
		back: './imagenes/cuadro1.png',
		front: './imagenes/imagen8.png',
		item: 8,
		question_image: './imagenes/pregunta8.jpg',
		a: {
			top: '46%',
			left: '9.9%',
			alert_image: './imagenes/verde8.png',
		},
		b: {
			top: '61.3%',
			left: '9.9%',
			incorrect_image: './imagenes/rojo8.png',
		},
		c: {
			top: '0%',
			left: '0%',
			incorrect_image: './imagenes/rojo8.png',
		},
		d: {
			top: '0%',
			left: '0%',
			incorrect_image: './imagenes/rojo8.png',
		},
		correct: 'a',
		correct_image: './imagenes/respuesta-8.png',
	},
	{
		back: './imagenes/cuadro1.png',
		front: './imagenes/imagen3.png',
		item: 3,
		question_image: './imagenes/pregunta3.jpg',
		a: {
			top: '46%',
			left: '8.9%',
			incorrect_image: './imagenes/rojo3.png',
		},
		b: {
			top: '62.1%',
			left: '9.7%',
			alert_image: './imagenes/verde3.png',
		},
		c: {
			top: '0%',
			left: '0%',
			incorrect_image: './imagenes/rojo3.png',
		},
		d: {
			top: '0%',
			left: '0%',
			alert_image: './imagenes/verde3.png',
		},
		correct: 'b',
		correct_image: './imagenes/respuesta-3.png',
	},
	{
		back: './imagenes/cuadro1.png',
		front: './imagenes/imagen6.png',
		item: 6,
		question_image: './imagenes/pregunta6.jpg',
		a: {
			top: '33.7%',
			left: '8.9%',
            width: '43%',
			incorrect_image: './imagenes/rojo6.png',
		},
		b: {
			top: '45.9%',
			left: '8.9%',
            width: '43%',
			alert_image: './imagenes/verde6.png',
		},
		c: {
			top: '58.8%',
            width: '43%',
			left: '8.9%',
			incorrect_image: './imagenes/rojo6.png',
		},
		d: {
			top: '70.7%',
            width: '43%',
			left: '8.9%',
			incorrect_image: './imagenes/rojo6.png',
		},
		correct: 'b',
		correct_image: './imagenes/respuesta-6.png',
	},
]
